config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    devise_for :users
    root "home#index"
    resources :posts do
      resources :likes
      resources :comments
    end
    resources :finds
    get "/edit-password" => "users#edit_password"
    resource :comments
    resources :users do
      resources :notifications
      member do
        resources :relationships
      end
    end
  end
  mount ActionCable.server => "/cable"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  delegate :name, :avatar, to: :user, allow_nil: true

  validates :content, presence: true, length: {maximum: Settings.content_max}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_post
  before_action :logged_in_user, only: %i(create destroy)
  before_action :correct_comment, only: :destroy

  def create
    @comment = @post.comments.build comment_params
    @comment.user_id = current_user.id

    if @comment.save
      respond_to do |format|
        format.html{redirect_to root_path}
        format.js
      end
    else
      flash.alert = t "comment_fail"
      render root_path
    end
  end

  def destroy
    if @comment.destroy?
      respond_to do |format|
        format.html{redirect_to request.referrer || root_url}
        format.js
      end
    else
      flash.alert = t "del_fail"
      render "home/index"
    end
  end

  private

  def comment_params
    params.require(:comment).permit :content
  end

  def load_post
    @post = Post.find_by id: params[:post_id]
    return if @post
    flash.alert = t "post_not_found"
    redirect_to root_url
  end

  def correct_comment
    @comment = current_user.comments.find_by id: params[:id]
    return if @comment
    flash.alert = t "comment_not_found"
    redirect_to root_url
  end
end

app/views/comments/_comment.html.erb
<div class="comment">
    <%= image_tag comment.avatar.to_s %>
  <div class="comment-content">
    <%= link_to comment.name, comment.user %>

    <%= comment.content %></br>

    <span class="timestamp">
      <%= time_ago_in_words comment.created_at %>

      <% if comment.user == current_user %>
        <%= link_to t("btn_del"), post_comment_path(post, comment),
          method: :delete, data: { confirm: t("del_confirm") }, class: "delete-comment" %>
      <% end %>
    </span>
  </div>
</div>

app/views/comments/create.js.erb
$('#comments-<%= @post.id %>').append('<%= j render 'comments/comment', post: @post, comment: @comment %>');
$('#comment-content-<%= @post.id %>').val('');
$('#comment-count-<%= @post.id %>').html('<%= @post.comments.size %><i class="fa fa-comments-o fa-lg"></i>');

app/views/comments/destroy.js.erb
$('#comments-<%= @post.id %>').html("<%= j render @post.comments, post: @post, comment: @comment %>");
$('#comment-count-<%= @post.id %>').html('<%= @post.comments.size %><i class="fa fa-comments-o fa-lg"></i>');