config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    devise_for :users
    root "home#index"
    resources :posts do
      resources :likes
      resources :comments
    end
    resources :finds
    get "/edit-password" => "users#edit_password"
    resource :comments
    resources :users do
      resources :notifications
      member do
        resources :relationships
      end
    end
  end
  mount ActionCable.server => "/cable"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post
  before_action :find_like, only: [:destroy]

  def create
    @post.likes.create user_id: current_user.id
    respond_to do |format|
      format.html{redirect_to root_path}
      format.js
    end
  end

  def destroy
    @like.destroy
    respond_to do |format|
      format.html{redirect_to root_path}
      format.js
    end
  end

  private

  def find_post
    @post = Post.find_by id: params[:post_id]
  end

  def find_like
    @like = @post.likes.find_by id: params[:id]
  end
end

app/views/likes/_like.html.erb
<%= form_for post.likes.build, url: post_likes_path(post), remote: true do |f| %>
  <%= f.submit t("like"), class: "btn-like" %>
<% end %>

app/views/likes/_like_form.html.erb
<div id="like-form-<%= post.id %>">
  <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
  <% if pre_like %>
    <%= render "likes/unlike", post: post, pre_like: pre_like %>
  <% else %>
    <%= render "likes/like", post: post %>
  <% end %>
</div>

app/views/likes/_unlike.html.erb
<%= form_for post.likes.find_by(post_id: post.id ), url: post_like_path(post, pre_like),
             html: {method: :delete},
             remote: true do |f| %>
  <%= f.submit t("unlike"), class: "btn-like" %>
<% end %>

app/views/likes/create.js.erb
$('#like-form-<%= @post.id %>').html('<%= j(render("likes/unlike", post: @post, pre_like: Like.find_by(post_id: @post.id))) %>');
$('#likes-<%= @post.id %>').html('<%= @post.likes.count %><i class="fa fa-heart"></i>');

app/views/likes/destroy.js.erb
$('#like-form-<%= @post.id %>').html('<%= j(render("likes/like", post: @post)) %>');
$('#likes-<%= @post.id %>').html('<%= @post.likes.count %><i class="fa fa-heart"></i>');