config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    devise_for :users
    root "home#index"
    resources :posts do
      resources :likes
      resources :comments
    end
    resources :finds
    get "/edit-password" => "users#edit_password"
    resource :comments
    resources :users do
      resources :notifications
      member do
        resources :relationships
      end
    end
  end
  mount ActionCable.server => "/cable"
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
  has_many :active_relationships, class_name:  Relationship.name,
           foreign_key: :follower_id,
           dependent:   :destroy

  has_many :passive_relationships, class_name: Relationship.name,
           foreign_key: :followed_id,
           dependent: :destroy

  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :generals, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :notifications

  mount_uploader :avatar, AvatarUploader
  validates :name, presence: true, length: {minimum: Settings.name_min,
                                            maximum: Settings.name_max}
  validates :user_name, presence: true, length: {minimum: Settings.name_min,
                                                 maximum: Settings.name_max}

  scope :find_user, (lambda do
    where "lower(name) LIKE :search", search: "%#{@parameter}%"
  end)

  def follow other_user
    following << other_user
  end

  def un_follow other_user
    following.delete other_user
  end

  def following? other_user
    following.include? other_user
  end

  def feed
    followings = Relationship.select(:followed_id).where(follower_id: id).to_sql
    Post.order_posts.where "user_id IN (#{followings})
      OR user_id = :user_id", user_id: id
  end

  def current_user? user
    user == self
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: %i(edit show update)
  before_action :verify_user, only: %i(edit update)
  before_action :verify_admin, only: :index

  def index; end

  def show
    @posts = @user.posts.order_posts.page(params[:page]).per Settings.per_page
    return unless user_signed_in?
    @post = current_user.posts.build
  end

  def edit; end

  def update
    if current_user.update user_params
      redirect_to current_user
      flash.notice = t "users.edit.update_success"
    else
      render :edit
    end
  end

  private

  def verify_user
    break_out unless current_user? @user
  end

  def load_user
    @user = User.find_by id: params[:id]

    return if @user
    flash.alert = t "no_pages_found"
    redirect_to root_path
  end

  def user_params
    params.require(:user).permit :user_name, :name, :avatar,
      :website
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user? user
    user == current_user
  end
end

app/views/users/_follow.html.erb
<%= form_for current_user.active_relationships.build, remote: true do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit t("follow"), class: "edit-profile", id: "follow" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render "unfollow" %>
    <% else %>
      <%= render "follow" %>
    <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with model: current_user, local: true, html: {class: "form-horizontal form-edit-user"} do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="form-group row">
    <div class="col-sm-3 col-form-label">
      <% if current_user.avatar?%>
        <%= image_tag current_user.avatar.to_s, class: "avatar" %>
      <% else %>
        <%= image_tag "ocean.jpg", class: "avatar" %>
      <% end %>
    </div>
    <div class="col-sm-9">
        <p class="username"><%= t "users.show.edit_profile" %></p>
        <span class="picture">
        <%= f.file_field :avatar, accept: "image/jpeg,image/gif,image/png" %>
        </span>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :name, t("name"), class: "col-sm-3 col-form-label" %>
    <div class="col-sm-9">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :user_name, t("user_name") , class: "col-sm-3 col-form-label" %>
    <div class="col-sm-9">
      <%= f.text_field :user_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :website, t("web_site"), class: "col-sm-3 col-form-label" %>
    <div class="col-sm-9">
      <%= f.text_field :website, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :email, class: "col-sm-3 col-form-label" %>
    <div class="col-sm-9">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-3">
    </div>
    <div class="col-sm-9">
      <%= f.submit t("submit"), class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/users/_form_password.html.erb
<%= form_with model: current_user, local: true, html: {class: "form-horizontal form-edit-user"} do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="form-group row">
    <div class="col-sm-3 col-form-label">
      <% if current_user.avatar?%>
        <%= image_tag current_user.avatar.to_s, class: "avatar" %>
      <% else %>
        <%= image_tag "ocean.jpg", class: "avatar" %>
      <% end %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :password, class: "col-sm-3 col-form-label" %>
    <div class="col-sm-9">
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :password_confirmation, class: "col-sm-3 col-form-label" %>
    <div class="col-sm-9">
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-3">
    </div>
    <div class="col-sm-9">
      <%= f.submit t("submit"), class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/users/_stat.html.erb
<% @user ||= current_user %>
<ul class="posts">
  <li><span><%= @user.posts.size %> </span><%= t "posts" %></li>
  <li>
    <%= link_to relationship_path @user, follow_path: :following do %>
      <span id="following" class="posts"><%= @user.following.size %></span>
      <%= t "users.show_follow.following" %>
    <% end %>
  </li>
  <li>
    <%= link_to relationship_path @user, follow_path: :followers do %>
      <span id="followers" class="posts"><%= @user.followers.size %></span>
      <%= t "users.show_follow.followers" %>
    <% end %></li>
</ul>

app/views/users/_unfollow.html.erb
<%= form_for current_user.active_relationships.find_by(followed_id: @user.id),
             html: {method: :delete},
             remote: true do |f| %>
  <%= f.submit t("un_follow"), class: "edit-profile" %>
<% end %>

app/views/users/edit.html.erb
<div class="user-edit-page">
  <div class="actions">
    <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
      <%= link_to t("users.show.edit_profile"), edit_user_path(current_user), class: "nav-link" %>
      <%= link_to t("users.edit.change_password"), edit_password_path, class: "nav-link" %>
      <%= link_to t("users.edit.authorized_applications"), user_notifications_path(current_user), class: "nav-link" %>
      <%= link_to t("users.edit.email_and_sms"), "#", class: "nav-link" %>
      <%= link_to t("users.edit.manage_contacts"), "#", class: "nav-link" %>
      <%= link_to t("users.edit.privacy_and_security"), "#", class: "nav-link" %>
    </div>
  </div>
  <div class="details tab-content">
    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
      <%= render "users/form" %>
    </div>
  </div>
</div>

app/views/users/edit_password.html.erb
<div class="user-edit-page">
  <div class="actions">
    <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
      <%= link_to t("users.show.edit_profile"), edit_user_path(current_user), class: "nav-link" %>
      <%= link_to t("users.edit.change_password"), edit_password_path, class: "nav-link" %>
      <%= link_to t("users.edit.authorized_applications"), user_notifications_path(current_user), class: "nav-link" %>
      <%= link_to t("users.edit.email_and_sms"), "#", class: "nav-link" %>
      <%= link_to t("users.edit.manage_contacts"), "#", class: "nav-link" %>
      <%= link_to t("users.edit.privacy_and_security"), "#", class: "nav-link" %>
    </div>
  </div>
  <div class="details tab-content">
    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
      <%= render "users/form_password" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="user-edit-page">
  <div class="actions">
    <!-- Left column -->
  </div>
  <div class="details">
    <!-- Right column -->
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="profile row">
    <div class="col-md-4 avatar">
      <div class="wrapper">
        <% if @user.avatar? %>
          <%= image_tag @user.avatar.to_s %>
        <% else %>
          <%= image_tag "ocean.jpg" %>
        <% end %>
       </div>
    </div>

    <div class="col-md-8 basic-info">
      <div class="user-wrapper">
        <h2 class="username"><%= @user.user_name %></h2>
        <% if user_signed_in? %>
          <% if current_user?@user %>
            <%= link_to edit_user_path current_user do %>
              <button class="edit-profile"><%= t ".edit_profile" %></button>
            <% end %>
          <% else %>
            <%= render "follow_form" %>
          <% end %>
        <% end %>
      </div>
      <%= render "stat" %>
      <h2 class="name"><%= @user.name %></h2>
      <h2 class="website"><%= @user.website %></h2>
    </div>
  </div>
</div>

<div class="user-tabs">

  <%= link_to "#", class: "tab active" do %>
    <i class="fa fa-th"></i>
    <%= t "pots" %>
  <% end %>

  <%= link_to "#", class: "tab" do %>
    <i class="fa fa-tv"></i>
    <%= t "igtv" %>
  <% end %>

  <%= link_to "#", class: "tab" do %>
    <i class="fa fa-bookmark"></i>
    <%= t "saved" %>
  <% end %>

  <%= link_to "#", class: "tab" do %>
    <i class="fa fa-tag"></i>
    <%= t "tagged" %>
  <% end %>
</div>

<div class="posts-wrapper">
  <% if @user.posts.any? %>
    <ul>
      <% @posts.each do |post| %>
        <%= render "posts/post", post: post %>
      <% end %>
    </ul>
    <%= paginate @posts, theme: "twitter-bootstrap-4" %>
  <% end %>
</div>