config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    devise_for :users
    root "home#index"
    resources :posts do
      resources :likes
      resources :comments
    end
    resources :finds
    get "/edit-password" => "users#edit_password"
    resource :comments
    resources :users do
      resources :notifications
      member do
        resources :relationships
      end
    end
  end
  mount ActionCable.server => "/cable"
end

app/views/layouts/_footer.html.erb
<footer class="container footer">
  <nav class="navbar d-flex">
    <ul>
      <li><%= link_to t(".about"), "#" %></li>
      <li><%= link_to t(".support"), "#" %></li>
      <li><%= link_to t(".hashtag"), "#" %></li>
      <li><%= link_to t(".eng"), locale: "en" %></li>
      <li><%= link_to t(".vie"), locale: "vi" %></li>
    </ul>
    <p><%= t".slogan" %></p>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light bg-light d-flex">
  <div class="container">
    <div class="logo">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= fa_stacked_icon "camera inverse", base: "circle"%>
        <%= t "title" %>
      <% end %>
    </div>
    <div class="m-auto">
      <%= form_tag finds_path, method: :get, class: "form-inline search-form" do  %>
        <%= search_field_tag :search, params[:search], placeholder: t(".search_holder"), class: "form-control mr-sm-2" %>
        <div class="input-group-btn">
          <%= button_tag class: "input-group-text" ,id: "btnGroupAddon" do %>
            <i class="fa fa-search"></i>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="user-section">
      <%= link_to "#" do %>
        <i class="fa fa-compass"></i>
      <% end %>

      <% if user_signed_in? %>

        <%= link_to user_notifications_path current_user do %>
          <i class="fa fa-bell" id="open_notification"></i>
          <%= render "notifications/counter", counter: current_user.notifications.count %>
        <% end %>

        <%= link_to user_path current_user do %>
          <i class="fa fa-user"></i>
        <% end %>
        <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path do %>
          <i class="fa fa-sign-in"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t "title" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <!--Main content-->
    <main class="container" style="min-height: 500px;">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </main>

    <%= render "layouts/footer" %>
  </body>
</html>